language: java
jdk:
  - openjdk8
script: >
  gradle clean build && 
  mkdir build-process && 
  cd build-process && 
  git clone https://github.com/vrapio/rmf-codegen.git && 
  git clone https://github.com/commercetools/commercetools-api-reference.git && 
  cd commercetools-api-reference && 
  export TEST_RAML_FILE="$(realpath update-actions.raml)" && 
  cd .. && 
  cd rmf-codegen && 
  gradle clean build && 
  gradle clean build bintrayUpload --info