on:
  push:
    branches:
      - master
    tags:
      - '[1-9][0-9]?.[0-9]+.[0-9]+'

name: AutoRelease

jobs:
  release:
    name: Build and release

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Retrieve branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Build and Test
        run: ./gradlew --build-cache clean test

      - name: Release
        if: startsWith( github.ref, 'refs/tags/') == false
        run: ./gradlew --build-cache bintrayUpload writeVersionToReadme --info --stacktrace
        env:
          CTP_BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          CTP_BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}

      - name: Release tag
        if: startsWith( github.ref, 'refs/tags/')
        run: ./gradlew clean build -x check -Pversion=$SOURCE_TAG --info --stacktrace
        env:
          CTP_BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          CTP_BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: startsWith( github.ref, 'refs/tags/') == false
        with:
          commit_message: "TASK: Updating version in README"
          commit_user_name: Auto Mation
          commit_user_email: automation@commercetools.com
          commit_author: Auto Mation <automation@commercetools.com>
