on:
  - push
  - workflow_dispatch

name: CI

jobs:
  integrationTest:
    name: Integration tests

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'

      - name: Retrieve branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Run integration tests
        run: ./gradlew clean build runMainMethodThreadLeakTest
        env:
          CTP_CLIENT_ID: ${{ secrets.CTP_CLIENT_ID }}
          CTP_CLIENT_SECRET: ${{ secrets.CTP_CLIENT_SECRET }}
          CTP_PROJECT_KEY: ${{ secrets.CTP_PROJECT_KEY }}
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
          CTP_JVM_SDK_LOG_LEVEL: OFF
