on:
  release:
    types:
      - released

name: MavenSync

jobs:
  mavensync:
    name: Sync to Maven

    runs-on: ubuntu-latest

    if: startsWith( github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Retrieve branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - run: ./gradlew -Pversion=$SOURCE_TAG bintrayMavenSync --info --stacktrace
        env:
          CTP_BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          CTP_BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
          CTP_OSS_USER: ${{ secrets.OSS_USER }}
          CTP_OSS_SECRET: ${{ secrets.OSS_SECRET }}
          MAVEN_SYNC: "true"
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
