on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

name: AutoRelease

jobs:
  release_tag:
    name: Build and release tag

    runs-on: ubuntu-latest

    if: startsWith( github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: sdk

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Retrieve branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - run: ./gradlew -Pversion=$SOURCE_TAG clean test javadoc bintrayUpload publish writeVersionToReadme --info --stacktrace
        working-directory: sdk
        env:
          CTP_BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          CTP_BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
          CTP_OSS_USER: ${{ secrets.OSS_USER }}
          CTP_OSS_SECRET: ${{ secrets.OSS_SECRET }}
          MAVEN_SYNC: "true"
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}

      - name: Create GH Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          path: build_master

      - run: ./gradlew -Pversion=$SOURCE_TAG writeVersionToReadme
        working-directory: build_master
        env:
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: build_master
          commit_message: "TASK: Updating version in README"
          commit_user_name: Auto Mation
          commit_user_email: automation@commercetools.com
          commit_author: Auto Mation <automation@commercetools.com>

  docs:
    name: Build and release docs

    runs-on: ubuntu-latest
    needs: [release_tag]
    if: startsWith( github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: sdk

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: doc
          ref: gh-pages

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - run: ./gradlew alljavadoc
        working-directory: sdk

      - run: rm -rf doc/javadoc && mv sdk/build/docs/javadoc doc

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: doc
          commit_message: "Update javadoc"
          commit_user_name: Auto Mation
          commit_user_email: automation@commercetools.com
          commit_author: Auto Mation <automation@commercetools.com>
