on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

    branches:
      - master

name: AutoRelease

jobs:
#  release:
#    name: Build and release
#
#    runs-on: ubuntu-latest
#
#    if: startsWith( github.ref, 'refs/tags/') == false
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Setup Java
#        uses: actions/setup-java@v1
#        with:
#          java-version: '8'
#
#      - name: Build and Test
#        run: ./gradlew --build-cache clean test
#
#      - name: Release
#        run: ./gradlew --build-cache bintrayUpload writeVersionToReadme --info --stacktrace
#        env:
#          CTP_BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
#          CTP_BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
#
#      - uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          commit_message: "TASK: Updating version in README"
#          commit_user_name: Auto Mation
#          commit_user_email: automation@commercetools.com
#          commit_author: Auto Mation <automation@commercetools.com>

  release_tag:
    name: Build and release tag

    runs-on: ubuntu-latest

    if: startsWith( github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Retrieve branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - run: ./gradlew -Pversion=$SOURCE_TAG clean test bintrayUpload writeVersionToReadme --info --stacktrace
        env:
          CTP_BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          CTP_BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}

      - name: Create GH Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

#      - uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          commit_message: "TASK: Updating version in README"
#          commit_user_name: Auto Mation
#          commit_user_email: automation@commercetools.com
#          commit_author: Auto Mation <automation@commercetools.com>
